# Changes here will be overwritten by Copier
_commit: 37f89c1
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: dev@1kbgz.com
github: tkp-aliases
project_description: Alias for nbprint
project_name: ipyprint
python_version_primary: '3.11'
team: the ipyprint authors
